{% set name = "retrying" %}
{% set version = "1.3.4" %}
{% set bundle = "tar.gz" %}
{% set hash = "345da8c5765bd982b1d1915deb9102fd3d1f7ad16bd84a9700b85f64d24e8f3e" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - six >=1.7.0

test:
  imports:
    - retrying

about:
  home: https://github.com/rholder/retrying
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Simplify the task of adding retry behavior to just about anything.'
  dev_url: https://github.com/rholder/retrying

extra:
  recipe-maintainers:
    - pmlandwehr
