{% set name = "retrying" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4d69fc16cf47912e145ff206c33d2fec8f1fdbb81ecd2de1b9188e016a810dd0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - retrying
  commands:
    - pip check

about:
  home: https://github.com/rholder/retrying
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Simplify the task of adding retry behavior to just about anything.'
  dev_url: https://github.com/rholder/retrying

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
