{% set name = "retrying" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13859d82b786d6d76df33d59a2372623deed45d57028018092dec612c45064d8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - six >=1.7.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - retrying
  commands:
    - pip check

about:
  home: https://github.com/rholder/retrying
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'Simplify the task of adding retry behavior to just about anything.'
  dev_url: https://github.com/rholder/retrying

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
